// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from "./client";
import type {
    LoginUserData,
    LoginUserError,
    LoginUserResponse,
    CreateUserData,
    CreateUserError,
    CreateUserResponse,
    ListUsersData,
    ListUsersError,
    ListUsersResponse,
    EditUserData,
    EditUserError,
    EditUserResponse,
    ListEmployeesError,
    ListEmployeesResponse,
    GetProductsListData,
    GetProductsListError,
    GetProductsListResponse,
    CreateProductData,
    CreateProductError,
    CreateProductResponse,
    EditProductData,
    EditProductError,
    EditProductResponse,
    CreateSalesRequestData,
    CreateSalesRequestError,
    CreateSalesRequestResponse,
    ListProductOrdersData,
    ListProductOrdersError,
    ListProductOrdersResponse,
    FinishOrderData,
    FinishOrderError,
    FinishOrderResponse,
    GetOrderPdfData,
    GetOrderPdfError,
    GetOrderPdfResponse,
} from "./types.gen";

export const client = createClient(createConfig());

export class UserService {
    /**
     * Login User
     */
    public static loginUser<ThrowOnError extends boolean = false>(
        options: Options<LoginUserData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            LoginUserResponse,
            LoginUserError,
            ThrowOnError
        >({
            ...options,
            url: "/user/login",
        });
    }

    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = false>(
        options: Options<CreateUserData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            CreateUserResponse,
            CreateUserError,
            ThrowOnError
        >({
            ...options,
            url: "/user/create",
        });
    }

    /**
     * Create User
     */
    public static listUsers<ThrowOnError extends boolean = false>(
        options: Options<ListUsersData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            ListUsersResponse,
            ListUsersError,
            ThrowOnError
        >({
            ...options,
            url: "/user/list",
        });
    }

    /**
     * Edit User
     */
    public static editUser<ThrowOnError extends boolean = false>(
        options: Options<EditUserData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            EditUserResponse,
            EditUserError,
            ThrowOnError
        >({
            ...options,
            url: "/user/edit",
        });
    }

    /**
     * List Employees
     */
    public static listEmployees<ThrowOnError extends boolean = false>(
        options?: Options<unknown, ThrowOnError>
    ) {
        return (options?.client ?? client).get<
            ListEmployeesResponse,
            ListEmployeesError,
            ThrowOnError
        >({
            ...options,
            url: "/user/employees",
        });
    }
}

export class ProductsService {
    /**
     * Get Products List
     */
    public static getProductsList<ThrowOnError extends boolean = false>(
        options: Options<GetProductsListData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            GetProductsListResponse,
            GetProductsListError,
            ThrowOnError
        >({
            ...options,
            url: "/products/list",
        });
    }

    /**
     * Create Product
     */
    public static createProduct<ThrowOnError extends boolean = false>(
        options: Options<CreateProductData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            CreateProductResponse,
            CreateProductError,
            ThrowOnError
        >({
            ...options,
            url: "/products/create",
        });
    }

    /**
     * Edit Product
     */
    public static editProduct<ThrowOnError extends boolean = false>(
        options: Options<EditProductData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            EditProductResponse,
            EditProductError,
            ThrowOnError
        >({
            ...options,
            url: "/products/edit",
        });
    }

    /**
     * Create Sales Request
     */
    public static createSalesRequest<ThrowOnError extends boolean = false>(
        options: Options<CreateSalesRequestData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            CreateSalesRequestResponse,
            CreateSalesRequestError,
            ThrowOnError
        >({
            ...options,
            url: "/products/create-sales-request",
        });
    }

    /**
     * List Product Orders
     */
    public static listProductOrders<ThrowOnError extends boolean = false>(
        options: Options<ListProductOrdersData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            ListProductOrdersResponse,
            ListProductOrdersError,
            ThrowOnError
        >({
            ...options,
            url: "/products/list-product-orders",
        });
    }

    /**
     * List Product Orders
     */
    public static finishOrder<ThrowOnError extends boolean = false>(
        options: Options<FinishOrderData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            FinishOrderResponse,
            FinishOrderError,
            ThrowOnError
        >({
            ...options,
            url: "/products/finish-order",
        });
    }

    /**
     * Get Order Pdf
     */
    public static getOrderPdf<ThrowOnError extends boolean = false>(
        options: Options<GetOrderPdfData, ThrowOnError>
    ) {
        return (options?.client ?? client).post<
            GetOrderPdfResponse,
            GetOrderPdfError,
            ThrowOnError
        >({
            ...options,
            url: "/products/get-order-pdf",
        });
    }
}
